### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by jagribble** [benewen96/cirrus-kb#1]
As discussed the '=>' breaks when in safari. This means the submission box isn't shown properly and the search function does not work. But I can still view all articles. 

Well done :)

**Comment by benewen96** [comment]
This will be resolved soon, arrow function support is poor in Safari, I plan to implement webpack support with babel shortly.

**Comment by benewen96** [comment]
Issue resolved. Browsers tested: IE9, Safari, Chrome
